### PR TITLE
Update InferFunctionArguments.tsx

### PR DESCRIPTION
**Pull request by verheyenkoen**
Fixed "JSON" to "Json" casing (great article btw!)

### CODE REVIEW

**Comment by verheyenkoen** [comment]
Scratch that. Circular reference appear to be invalid. Should have tested first...

**Comment by captain-yossarian** [comment]
@verheyenkoen no problem. Thank you for your intention and for your feedback! Have a nice day!

**Comment by verheyenkoen** [comment]
Was wrong again. Apparently it does work but I tried (locally) to replace your `| { [prop: string]: Json }` with `| Record<PropertyKey, Json>` and that caused a circular reference error: "Type alias 'Json' circularly references itself (2456)" which is pretty weird as those two are equivalent I guess.

**Comment by captain-yossarian** [comment]
@verheyenkoen could you please provide reproducible example in playground ?

**Comment by verheyenkoen** [comment]
@captain-yossarian Not sure which one you want but this is [the code as I've altered it](https://www.typescriptlang.org/play?#code/C4TwDgpgBAUgzgewHZQLwCgpQD5SQVwBtDMco5gAnASyQHNTcCBbAIwksalYQUIgCGSLgEFKlASAA88ZAD4uAb1JYA2mEoIwALnJVadALq7ZwrAF906AMbIKUAGa80UKaQDSEEFAgAPYBBIACZwUAAKmpCUoJ4gADSkAGoChPjQfgHBoaYJWAAqPv6BIVAAShC2lEFSsXFQyakQCnIAFAK6eQCUaHJQAlYA9ANQtkj2Tgi6UhFaHDFedTlQin26ACwATADc3LoARAAWEMQIezuWEy0r7VCbday6AORHJ49Q5p1AA) (no errors) and this is [the code with the `Record<>` instead of object liberal](https://www.typescriptlang.org/play?#code/C4TwDgpgBAUgzgewHZQLwCgpQD5SQVwBtDMco5gAnASyQHNTcCBbAIwksalYQUIgCGSLgEFKlASAA88ZAD4uAJQgBjBJQAmUgAqUEkSqADSEEABpYiJAvRqkFKADNeaKFNImQUCAA9gEJA04KF19DmNTM1IANQFCfGhff0Dg2SQorAAVbz8AoKhlNU0pTwtY+IgFOQAKAQAuKEyASjQ5KAF0dAB6Lqg7B2cEBp09AwjzS2QLAG92hoAWACYAbm4GgCIACwhiBHXVgF90QerZ+qgli1YGgHJt3ZuoA6agA) (1 error).

I also added another commit as the same problem occurred twice.

**Comment by captain-yossarian** [comment]
@verheyenkoen there is a difference between `{ [prop: string]: Json }` and `Record<PropertyKey, Json>`. See signature: `[prop: string]` and `[P in K]`. First one is an `anonymous interface` (not official name) second one is mapped type. Please see the difference between types and interfaces [here](https://stackoverflow.com/questions/37233735/interfaces-vs-types-in-typescript#answer-64971386) . From what I remember, types are lazy evaluated whereas interfaces are eagerly evaluated.

**Pull request closed without merging**
